### PR TITLE
MOTECH-2232 pinned horizontal scroll bar in Server Log

### PR DESCRIPTION
**Pull request by weronika-ciecierska**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by sebbrudzinski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
@pgesek OK to merge

**Pull request merged**
