### PR TITLE
MOTECH-2758: String format modal broken

### PR DESCRIPTION
**Pull request by 0nat**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by mkruszynski** [comment]
test this please

**Comment by mkruszynski** [comment]
@kmadej it looks good to me

**Pull request merged**
