### PR TITLE
MOTECH-2207 Change buttons colors and position according to given style guide

### PR DESCRIPTION
**Pull request by martokarski**
- Buttons that immedately effect the current screen or object in a row: Pull to the right
- Buttons that are secondary (such as filtering): Pull to the left
- All buttons are gray (.btn-default)
- Submit/Save/Confirm buttons are .btn-primary
- Add/create buttons are green (.btn-success)
- Destructive buttons (delete ect) are red (.btn-danger)

### CODE REVIEW

**Comment by martokarski** [comment]
test this please

**Comment by martokarski** [comment]
Thanks to @nickdotreid for quickly response.

I change colors according to description and position shown in screens:
mds-data-browser
mds-schema-editor
tasks

**Comment by kmadej** [comment]
I found few buttons with invalid colour : 

add option should be green and save should be blue while adding new option to combobox
screenshot from 2016-03-08 13 30 31

new lookup should be green
screenshot from 2016-03-08 13 31 09

new value should be green
screenshot from 2016-03-08 13 31 32

new metadata should be green
screenshot from 2016-03-08 13 31 44

new key/value pair should be green
screenshot from 2016-03-08 13 32 07


I'm not sure, however I think that in email logs 'filters' button should be on the left and 'export' on the right.
screenshot from 2016-03-08 13 30 54

**Comment by martokarski** [comment]
Added the changes from @kmadej comment.
Change color in: 
- Security / Manage Dynamic URLs
dynamic_url

- Admin / Log Options
log_options

- Tasks / New Task / Add filters
tasks_filter

**Comment by kmadej** [comment]
Admin -> Messages : Filters should be on the left, Refresh on the right side :
screenshot from 2016-03-10 11 55 15

Admin - > Settings: 'Add option' button should be green:
screenshot from 2016-03-10 11 55 43

**Comment by kmadej** [comment]
Additionally after meeting with Pawel, we established that colours of log buttons in Admin -> Server Log -> Log options should not be changed.

**Comment by nickdotreid** [comment]
I'm ok with leaving the log level buttons looking like a rainbow, because the color are meaningful and well mapped... I think ideally we wouldn't be using the bootstrap css classes to add color, but lets get that when we migrate this interface over to the MOTECH UI...

@kmadej — good job catching all these details (there are a ton of them)

**Pull request merged**
