### PR TITLE
Motech-2274: Added provision to change year and month in the tasks datepicker

### PR DESCRIPTION
**Pull request by shanmukhm**
User now can select year and month from the tasks datepicker

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Pull request merged**
