### PR TITLE
MOTECH-2632 Changes between different openmrs configurations are not saving in tasks.

### PR DESCRIPTION
**Pull request by jablonskidawid**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kmadej** [comment]
@jablonskidawid the Tasks module is often used, this change can provide to a lot of bugs. I think that a more safety solution is to add set subject for every OpenMRS action similar to Commcare. For sure this change requires more research.

**Comment by jablonskidawid** [comment]
I closed this PR. There will be no changes in this repo.

**Pull request closed without merging**
