### PR TITLE
MOTECH-1269: Refactored history and trash handling

### PR DESCRIPTION
**Pull request by pgesek**
* made history/trash use InstanceLifecycleListeners
* history and trash now store relations as collections
  of numbers (ids), they no longer copy the whole tree
* made history/trash just copy properties without
  making queries for the db schema
* added DDE ITs for history handling

### CODE REVIEW

**Comment by sebbrudzinski** [comment]
test this 0.25

**Comment by pgesek** [comment]
test this 0.26

**Comment by pgesek** [comment]
tes this 0.25

**Comment by pgesek** [comment]
test this 0.25

**Comment by pgesek** [comment]
test this 0.25

**Pull request merged**
