### PR TITLE
MOTECH-1269 Add 'one to many' relationship case in migration for historical tables

### PR DESCRIPTION
**Pull request by martokarski**
This PR contains changes from https://github.com/motech/motech/pull/565.

It adds support for PostgreSQL DB and adds migration for 'one to many' relations in historical tables.

### CODE REVIEW

**Comment by kmadej** [comment]
test this psql

**Comment by PiotrZurawskiSolDevelo** [comment]
Checked. migration on MySQL is almost working, when I want to restore something from trash I get frozen MOTECH and error in the application logs: 
http://pastebin.com/VjngnYFw

I created task with fileters on MOTECH without this PR.
I changes few times values for instance of this filters.
Then I run MOTECH with PR.
I checked in tasks if everything is correct.
In MDS I changed values, and then I restore from history to value from MOTECH without changes.

**Comment by PiotrZurawskiSolDevelo** [comment]
Checked, migration for Postgresql is worked well. Same bug for trash appear here.

**Comment by martokarski** [comment]
test this psql

**Comment by kmadej** [comment]
test this please

**Comment by kmadej** [comment]
test this psql

**Comment by kmadej** [comment]
test this please

**Comment by kmadej** [comment]
test this psql

**Comment by kmadej** [comment]
test this psql

**Comment by kmadej** [comment]
test this psql

**Pull request merged**
