### PR TITLE
MOTECH-3102 The "Show bubble" checkbox doesn't work properly

### PR DESCRIPTION
**Pull request by srujan92**
Fixed the bubble bug.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kkedys** [comment]
@srujan92 The "show bubble" checkbox works now works properly with one exception.

1. Create a task with any Data Source and any Action.
2. Save the task
3. Go to this task to edit it
4. In action click "show bubbles" and change the "Channel". The bubbles hide. 

It show be necessary to standardize it, because when the task is being created, in this situation the bubbles don't hide.

**Comment by haribhansingh2011** [comment]
@kkedys I have updated the code please check it .

**Comment by srujan92** [comment]
@kkedys I have updated the code please check it.

**Comment by kkedys** [comment]
@kmadej, the issue is fixed.

**Pull request merged**
