### PR TITLE
MOTECH-1628 MDS Data Browser UI: Inline relationships

### PR DESCRIPTION
**Pull request by sebbrudzinski**
This pull request adds the ability to add, edit and remove relationships of an
instance, directly from a parent entity. The UI has been improved to present
related instances in a grid, or as embeded fields, if the relationship is 1:1.
Some backend code has also been adjusted and refactored, in order to 
work with the new views.

### CODE REVIEW

**Comment by sebbrudzinski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
1. We should not display negative (tempororary IDs in the relationship grids)
2. When I add a new relationship record using "Add new (entity name)", after I choose to add that related intance, the modal should dissapear. Currently it clears everything and stays opened with title only.
3. When I have more than one relationship in my entity, all the "Add new (entity name)" buttons open modal for one related entity only. For example, I've got relationshipField1, relationshipField2, relationshipField3 - I choose to add new relationship to relationshipField3, but the opened modal comes from relationshipField1

**Comment by wstrzelczyk** [comment]
I fixed the problems reported above

**Comment by pgesek** [comment]
Needs merge with master

**Comment by pgesek** [comment]
I tried using this with the Task entity on Firefox and it is falling apart:

1) I can add trigger, but I still see an empty modal after I do
2) I can't add anything else, I am shown an empty add trigger modal no matter what I add 
3) If I try to add a Task Config the grids get stuck on loading

**Comment by pgesek** [comment]
Nevermind, I had an old version

**Comment by pgesek** [comment]
Can we do something with the loading? When I click add new task, it looks bad when the grids are loading

**Comment by nickdotreid** [comment]
Are you talking about an MDS tasks instance or the Tasks UI?

In the tasks UI I'm planning to change the routes to use route.resolve...
so that slow data loads happen *before* the UI changes... then the data
gets directed directly into the controller

See: https://docs.angularjs.org/api/ngRoute/provider/$routeProvider

I'm not sure where I'll throw the UI-blocking code... but I bet there is a
nice event somewhere...

**Comment by pgesek** [comment]
@nickdotreid I'm talking about adding a new task in MDS. When I do that, the grids for related field collection start loading sort of on top of the greyed out area, which does not look good imo.

**Comment by pgesek** [comment]
The issue is fixed, however there exists with clearing field types.

Repro: 

1) Go to 'Add task' in MDS
2) Without refreshing go to 'Add MotechUser' in MDS

The MotechUser fields such as external id are now treated as relationship fields, which is not correct. Doing anything with the fields fails.

**Comment by pgesek** [comment]
Remove the comments

**Pull request merged**
