### PR TITLE
MOTECH-2324: Changed the default name of Character from 'char' to 'character'

### PR DESCRIPTION
**Pull request by shanmukhm**
- database is migrated to version-5

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
test this psql

**Pull request merged**
