### PR TITLE
MOTECH-1932: Refactored display handling for CSV export

### PR DESCRIPTION
**Pull request by pgesek**
* Allow more customization
* Reused logic from InstanceServiceImpl

### CODE REVIEW

**Comment by kmadej** [comment]
I checked :
- exporting comboboxes with enum display names
- exporting relationship field with UIRepresentation
- exporting relationship field with toString() method
- exporting relationship field without toString() method

It works correctly. However I noticed that after this changes, enum display names are missing spaces in MDS data browser grid. In exported csv file it is ok.

**Comment by kmadej** [comment]
Also there is a problem with parsing collection of string. Can you change this in this PR ?
You should change line 321 in TypeHelper to breakStringForCollection(str). And you can test this in TypeHelperTest. Just add string with spaces in line 223 in TypeHelperTest.

Additionally please rebase branch with master.

**Comment by kmadej** [comment]
:+1:

**Comment by pgesek** [comment]
test this please

**Comment by kmadej** [comment]
needs rebase

**Pull request merged**
