### PR TITLE
Added message for MOTECH-2739

### PR DESCRIPTION
**Pull request by PJSosnowski**
This message is required for MOTECH-2739 on motech-ui

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by jredlarski** [comment]
@kmadej Looks good to me

**Pull request merged**
