### PR TITLE
MOTECH-2032: Native strategy

### PR DESCRIPTION
**Pull request by tstalka**

### CODE REVIEW

**Comment by tstalka** [comment]
test this psql

**Comment by tstalka** [comment]
test this psql

**Comment by tstalka** [comment]
test this psql

**Comment by tstalka** [comment]
test this psql

**Comment by tstalka** [comment]
test this psql

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this psql

**Comment by pgesek** [comment]
test this please

**Pull request merged**
