### PR TITLE
MOTECH-2299: Fixed shortened task name in Task History in Task module

### PR DESCRIPTION
**Pull request by jredlarski**
Task name in Task History is shortened only if there is not enough space in a line.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kmadej** [comment]
It works correctly on chrome. On firefox a task name is still wrapped on bigger screen:

taskhistory

**Comment by kmadej** [comment]
Now it works properly also on the bigger screen

**Comment by kmadej** [comment]
test this please

**Pull request merged**
