### PR TITLE
MOTECH-2246 Add a status message action in tasks

### PR DESCRIPTION
**Pull request by jablonskidawid**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kmadej** [comment]
test this please

**Comment by mkwiatkowskisoldevelo** [comment]
@kmadej looks good to me

**Pull request merged**
