### PR TITLE
Add Component import to HelloWorldEventHandler

### PR DESCRIPTION
**Pull request by proteusvacuum**
The import statement was missing for the `@Component`

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by sebbrudzinski** [comment]
test this please

**Pull request merged**
