### PR TITLE
MOTECH-2163 Add metrics module.

### PR DESCRIPTION
**Pull request by justin-hayes**
Integrates the Dropwizard metrics library with the core platform,
exposes an API to register metrics with the system,
and allows implementers to stream metrics to Graphite.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
ok to test

**Comment by justin-hayes** [comment]
I'm going to close this pull request, fix the IT, and open a new one pointing at a feature branch this time around. My mistake.

**Pull request closed without merging**
