### PR TITLE
Motech-2401  Fixed the transclusion issue in the Tasks module

### PR DESCRIPTION
**Pull request by shanmukhm**
changed transclude from true to false in motechFileUpload directive

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Pull request merged**
