### PR TITLE
MOTECH-2485 Changed the request method to GET from POST

### PR DESCRIPTION
**Pull request by shanmukhm**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by wstrzelczyk** [comment]
If you change request method on back-end you should also change respectively on the front-end.

**Comment by shanmukhm** [comment]
@wstrzelczyk Sorry about that. I corrected them.

**Comment by sebbrudzinski** [comment]
test this please

**Comment by wstrzelczyk** [comment]
OK to merge

**Comment by pgesek** [comment]
test this please

**Pull request merged**
