### PR TITLE
cherry-pick MOTECH-2713: Error during creating new entity

### PR DESCRIPTION
**Pull request by jablonskidawid**
https://github.com/motech/motech/pull/633

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by martokarski** [comment]
test this please

**Pull request merged**
