### PR TITLE
Motech-2308: Strange behavior of minute slider in scheduler Date picker

### PR DESCRIPTION
**Pull request by shanmukhm**
- Made the two-way databinding in the datepicker directive optional
- Removed the minTime and maxTime options for the datepicker

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by nickdotreid** [comment]
@shanmukhm Can you rewrite the commit message to reflect what you changed, instead of the bug name in the ticket?

**Comment by shanmukhm** [comment]
@nickdotreid I edited the commit messages.

**Comment by nickdotreid** [comment]
@shanmukhm Your patch totally works, and I'm happy with your code...

Can you squash your commits? 6 commits for 5 lines seems a little much...

And please use the first comment line to describe what you changed, not the name of the JIRA ticket, and then put any needed details in the commit below.

"MOTECH-2308 Fixed strange behavior of minute slider in date picker directive" is a totally reasonable start to a commit message...

See [our commit message documentation,](http://docs.motechproject.org/en/latest/development/commit_message.html) or just bug me more...

(and sorry for being a pain in the butt about this)

**Comment by shanmukhm** [comment]
@nickdotreid I changed the history as you requested. I hope it looks good to you :)

**Comment by nickdotreid** [comment]
@pgesek I manually merged this pull request...

... and then realized I could have done this through the GUI (ooops)

I'm going to close this and mark the ticket ready for review...

**Pull request closed without merging**
