### PR TITLE
MOTECH-2719 Fixed delete task modal

### PR DESCRIPTION
**Pull request by jbanasiewicz**
Changed modal type to danger, to get red color, and deleted space between "Remove task" and "?".

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by jredlarski** [comment]
test this please

**Pull request merged**
