### PR TITLE
MOTECH-2781 MDS getInstances in POST not GET

### PR DESCRIPTION
**Pull request by filgomul**
Changed URL to use GET, not POST, to fetch data from the server

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by martokarski** [comment]
test this please

**Comment by filgomul** [comment]
For the same reason @sebbrudzinski mentioned in #643, we will close this ticket and do not merge the changes.

**Pull request closed without merging**
