### PR TITLE
MOTECH-2338: Timer class from metrics module moved to commons libraries

### PR DESCRIPTION
**Pull request by weronika-ciecierska**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by sebbrudzinski** [comment]
1. Remove unrealted commit from this branch (MOTECH-2232)
2. Change pull request title to something more descriptive

**Comment by sebbrudzinski** [comment]
One more thing that we may want to do, is dropping the "TimerService" interface and "TimerServiceImpl", since all that they do is returning an instance of "Timer". Let's just expose the Timer class and drop unnecessary boilerplate, which is this service interfce and service implementation. This also means that we do not need to keep the blueprint file with service definition.

**Comment by sebbrudzinski** [comment]
Changes will be address in a new pull request due to a mess with unrelated commits

**Pull request closed without merging**
