### PR TITLE
MOTECH-2011: Added dynamic triggers for Scheduler module

### PR DESCRIPTION
**Pull request by ngraczewski**

### CODE REVIEW

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this plese

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
@ngraczewski  needs merging with master

**Comment by ngraczewski** [comment]
test this please

**Comment by ngraczewski** [comment]
test this please

**Pull request merged**
