### PR TITLE
MOTECH-2150: Revert Angular 1.2.29 upgrade

### PR DESCRIPTION
**Pull request by pgesek**

### CODE REVIEW

**Comment by wstrzelczyk** [comment]
After deep investigation I think we do not need revert these commits.

**Comment by frankhuster** [comment]
Thanks man,
Can you explain why?

On Wed, Feb 3, 2016 at 7:53 AM, wstrzelczyk <notifications@github.com>
wrote:

> After deep investigation I think we do not need revert these commits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech/motech/pull/320#issuecomment-179305062>.
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by wstrzelczyk** [comment]
I explain it in ticket description.
https://applab.atlassian.net/browse/MOTECH-2150

**Comment by frankhuster** [comment]
Thanks!

**Pull request closed without merging**
