### PR TITLE
MOTECH-2269 Add new checkstyle - @RedundantImport check.

### PR DESCRIPTION
**Pull request by paulthalluri**
Added new checkstyle.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by sebbrudzinski** [comment]
test this please

**Comment by kmadej** [comment]
@paulthalluri checkstyle works ! :)

**Comment by paulthalluri** [comment]
Checked in the code to resolve the build issues caused due to redundant imports in few projects.

**Comment by sebbrudzinski** [comment]
test this please

**Pull request merged**
