### PR TITLE
MOTECH-2376: Consolidate Server Status API

### PR DESCRIPTION
**Pull request by palbecki**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
test this please

**Comment by kmadej** [comment]
test this please

**Pull request merged**
