### PR TITLE
MOTECH-1269 Add 'one to many' relationship case in migration for historical tables

### PR DESCRIPTION
**Pull request by 1stmateusz**

### CODE REVIEW

**Comment by 1stmateusz** [comment]
test this psql

**Comment by 1stmateusz** [comment]
test this psql

**Comment by kmadej** [comment]
test this please

**Comment by PiotrZurawskiSolDevelo** [comment]
Ckecked,  In MOTECH application without changes I created two instances for one entity, then I created history for both of instances.
I deleted one of instance and I run motech with changes from this PR.
* In instance which was not deleted I can see history from this instance and from deleted instance.
* When I restore deleted instance I can not see history of it.
* Deleted instance is correctly restored into entity but still is visible in trash.

**Comment by 1stmateusz** [comment]
test this psql

**Comment by 1stmateusz** [comment]
test this psql

**Comment by 1stmateusz** [comment]
test this please

**Comment by 1stmateusz** [comment]
test this psql

**Comment by PiotrZurawskiSolDevelo** [comment]
Checked again, now deleted instance is correctly restored from trash.
I can not see restored value in trash.

**Comment by 1stmateusz** [comment]
test this psql

**Comment by 1stmateusz** [comment]
test this psql

**Comment by kmadej** [comment]
@PiotrZurawskiSolDevelo 
I cannot reproduce this problem with wrong history rows. Can you verify this once again with the newest changes ?

**Comment by kmadej** [comment]
test this psql

**Comment by 1stmateusz** [comment]
test this psql

**Comment by kmadej** [comment]
@PiotrZurawskiSolDevelo 
I have finally reproduced this bug. It occurrs on the branch 0.27.X without this changes. The path to reproduce :
1. Create an instance in entity via MDS
2. Edit few times to create few history instances
3. Create second instance in the same entity
4. Edit few times to create few history instances
5. Delete second created instance
6. Go to history of first instance
7. There are history instances of the deleted instance

This is not only UI bug, I checked this in the database.

This bug doesn't occurr on the master branch

**Comment by kmadej** [comment]
@PiotrZurawskiSolDevelo 
Can you verify if this changes fixes mentioned bug with history ? If yes, we will merge it.

**Comment by PiotrZurawskiSolDevelo** [comment]
I checked this with PR and everything is working well. This fix resolve that problem.

**Pull request merged**
