### PR TITLE
MOTECH-2075 Tasks Module: NPE when parsing a null list

### PR DESCRIPTION
**Pull request by srujan92**
Added a null exception if condition for convertToList method.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Pull request merged**
