### PR TITLE
MOTECH-2514 Button "clear" should be blocked

### PR DESCRIPTION
**Pull request by saikrishna-beehyv**
fixed the issue where clear button is enable even if nothing is selected

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
test this please

**Comment by llavoie** [comment]
@saikrishna-beehyv  This needs a merge/rebase from master

**Comment by pgesek** [comment]
test this please

**Pull request merged**
