### PR TITLE
MOTECH-2805: Fix archetypes have wrong dependency for settings config

### PR DESCRIPTION
**Pull request by palbecki**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
@palbecki Please remove unused server.config from [pom.xml](https://github.com/motech/motech/blob/master/utils/archetypes/minimal-bundle-archetype/src/main/resources/archetype-resources/pom.xml#L187)

**Comment by jredlarski** [comment]
test this please

**Pull request merged**
