### PR TITLE
MOTECH-2563: Fixed Admin Queues/Topics 500 response. Detailed instructions.

### PR DESCRIPTION
**Pull request by mkruszynski**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by sebbrudzinski** [comment]
@mkruszynski Remove unnecessary commits and resolve conflicts (if any).

**Comment by sebbrudzinski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
@pgesek LGTM

**Pull request merged**
