### PR TITLE
MOTECH-3006 Added provision to retry multiple tasks at once

### PR DESCRIPTION
**Pull request by shanmukhm**
* Created a separate view for tasks history
* Added filters based on progress, task name and date of execution
* Added a button to retry all the failed tasks in current page

### CODE REVIEW

**Comment by kmadej** [comment]
@mjazdzdewski please pull this changes and check if feature works correctly

**Comment by mjazdzdewski** [comment]
I've found few issues:
1. Sometimes (usually after a recent task execution) the history page fails to load completly. It loads all the records, but fails to convert it to user friendly informations.
1_load_fail
2. When I filter tasks so it shows only some of the failed tasks when I use Retry all failed Tasks button MOTECH starts to fail: cannot load any data or properly switch page. It basically breaks [down.]
3. When I switch to History page it lacks grey font text above the tabs which shows in other pages of the Task module.
3_missing_grey_text
4. I have also some doubts about how Retry all failed Tasks works. More details can be found in JIRA comment by @kmadej .

**Comment by kmadej** [comment]
thanks @shanmukhm for corrections, @mjazdzdewski is now verifying this

**Comment by mjazdzdewski** [comment]
It looks good to me.

**Pull request merged**
