### PR TITLE
MOTECH-2783 Scheduler getJob in GET

### PR DESCRIPTION
**Pull request by filgomul**
Changed URL to use GET, not POST, to fetch data from the server

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by martokarski** [comment]
test this please

**Comment by martokarski** [comment]
test this please

**Comment by martokarski** [comment]
@kmadej Looks good to me

**Pull request merged**
