### PR TITLE
MOTECH-1606: Documentation for the  optimistic transactions

### PR DESCRIPTION
**Pull request by tstalka**
Change-Id: Ia76713b5c7b8b19740d2ec927eb322226839231a

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by pgesek** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Comment by tstalka** [comment]
test this please

**Pull request merged**
