### PR TITLE
MOTECH-1865: Added unique & required constraints to the domain

### PR DESCRIPTION
**Pull request by sebbrudzinski**
We were missing these on some classes, leaving the integrity
ultimately to the application level, which was far from perfect.

### CODE REVIEW

**Comment by pgesek** [comment]
test this 0.25

**Comment by pgesek** [comment]
test this 0.25

**Comment by pgesek** [comment]
test this 0.25.X

**Comment by pgesek** [comment]
Adding users is not working because of the unique constraint on openId in MotechUser. It works on regular 0.25.X with clear db. We can drop that constraints, it is not important.

**Comment by pgesek** [comment]
test this 0.25

**Comment by sebbrudzinski** [comment]
test this 0.25

**Comment by sebbrudzinski** [comment]
test this 0.25

**Comment by sebbrudzinski** [comment]
test this 0.25

**Pull request merged**
