### PR TITLE
MOTECH-2796 Refactor UI Scheduler to be URI state driven

### PR DESCRIPTION
**Pull request by PJSosnowski**
If user click edit on specific task or click schedule job in scheduler module, its driven by url rather than by function in ng-click.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kmadej** [comment]
This should be done on the new MOTECH-UI

**Pull request closed without merging**
